# Generated by Django 5.2.6 on 2025-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_grade_profile_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preference_gender',
            new_name='preferred_gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preference_age_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preference_age_min',
        ),
        migrations.AddField(
            model_name='profile',
            name='max_age_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
