# Generated by Django 5.2.6 on 2025-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_preference_gender_profile_preferred_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, choices=[('chemistry', 'Chemistry'), ('computer_engineering', 'Computer Engineering'), ('electronics', 'Electronics')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('both', '모두')], max_length=10, null=True),
        ),
    ]
