# Generated by Django 5.2.6 on 2025-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_university_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_age_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='min_age_preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_preference_down',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_preference_up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
